[2023-03-22T06:31:20.525+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T06:25:00+00:00 [queued]>
[2023-03-22T06:31:20.531+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T06:25:00+00:00 [queued]>
[2023-03-22T06:31:20.531+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T06:31:20.531+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-22T06:31:20.531+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T06:31:20.540+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): get_file> on 2023-03-22 06:25:00+00:00
[2023-03-22T06:31:20.544+0000] {standard_task_runner.py:55} INFO - Started process 7469 to run task
[2023-03-22T06:31:20.546+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'CarFine', 'get_file', 'scheduled__2023-03-22T06:25:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/CarFineDAG.py', '--cfg-path', '/tmp/tmp75_lhdxj']
[2023-03-22T06:31:20.546+0000] {standard_task_runner.py:83} INFO - Job 280: Subtask get_file
[2023-03-22T06:31:20.585+0000] {task_command.py:388} INFO - Running <TaskInstance: CarFine.get_file scheduled__2023-03-22T06:25:00+00:00 [running]> on host f331b8a34e72
[2023-03-22T06:31:20.633+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CarFine
AIRFLOW_CTX_TASK_ID=get_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T06:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T06:25:00+00:00
[2023-03-22T06:31:20.634+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-22T06:31:20.634+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget -P /home/*** https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json']
[2023-03-22T06:31:20.642+0000] {subprocess.py:86} INFO - Output:
[2023-03-22T06:31:20.645+0000] {subprocess.py:93} INFO - --2023-03-22 06:31:20--  https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json
[2023-03-22T06:31:20.651+0000] {subprocess.py:93} INFO - Resolving www.dl.dropboxusercontent.com (www.dl.dropboxusercontent.com)... failed: Temporary failure in name resolution.
[2023-03-22T06:31:20.651+0000] {subprocess.py:93} INFO - wget: unable to resolve host address ‘www.dl.dropboxusercontent.com’
[2023-03-22T06:31:20.651+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2023-03-22T06:31:20.659+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2023-03-22T06:31:20.661+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=CarFine, task_id=get_file, execution_date=20230322T062500, start_date=20230322T063120, end_date=20230322T063120
[2023-03-22T06:31:20.669+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 280 for task get_file (Bash command failed. The command returned a non-zero exit code 4.; 7469)
[2023-03-22T06:31:20.677+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T06:31:20.694+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
