[2023-03-22T07:52:10.006+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T07:45:00+00:00 [queued]>
[2023-03-22T07:52:10.012+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T07:45:00+00:00 [queued]>
[2023-03-22T07:52:10.012+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:52:10.012+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-22T07:52:10.012+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:52:10.021+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): get_file> on 2023-03-22 07:45:00+00:00
[2023-03-22T07:52:10.025+0000] {standard_task_runner.py:55} INFO - Started process 2975 to run task
[2023-03-22T07:52:10.027+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'CarFine', 'get_file', 'scheduled__2023-03-22T07:45:00+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/CarFineDAG.py', '--cfg-path', '/tmp/tmp6e92ejr0']
[2023-03-22T07:52:10.027+0000] {standard_task_runner.py:83} INFO - Job 353: Subtask get_file
[2023-03-22T07:52:10.067+0000] {task_command.py:388} INFO - Running <TaskInstance: CarFine.get_file scheduled__2023-03-22T07:45:00+00:00 [running]> on host ed9661b333ec
[2023-03-22T07:52:10.115+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CarFine
AIRFLOW_CTX_TASK_ID=get_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T07:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T07:45:00+00:00
[2023-03-22T07:52:10.116+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-22T07:52:10.116+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget -P /home/*** https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json']
[2023-03-22T07:52:10.123+0000] {subprocess.py:86} INFO - Output:
[2023-03-22T07:52:10.126+0000] {subprocess.py:93} INFO - --2023-03-22 07:52:10--  https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json
[2023-03-22T07:52:18.396+0000] {subprocess.py:93} INFO - Resolving www.dl.dropboxusercontent.com (www.dl.dropboxusercontent.com)... failed: Temporary failure in name resolution.
[2023-03-22T07:52:18.397+0000] {subprocess.py:93} INFO - wget: unable to resolve host address ‘www.dl.dropboxusercontent.com’
[2023-03-22T07:52:18.397+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2023-03-22T07:52:18.408+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2023-03-22T07:52:18.411+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=CarFine, task_id=get_file, execution_date=20230322T074500, start_date=20230322T075210, end_date=20230322T075218
[2023-03-22T07:52:18.424+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 353 for task get_file (Bash command failed. The command returned a non-zero exit code 4.; 2975)
[2023-03-22T07:52:18.443+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T07:52:18.464+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
